# Deployment Statuses
PENDING = 'PENDING'
SMOKING = 'SMOKING'
SMOKE_SUCCESS = 'SMOKE_SUCCESS'
SMOKE_SUCCESS_BRAKED = 'SMOKE_SUCCESS_BRAKED'
SMOKE_FAILURE_BRAKED = 'SMOKE_FAILURE_BRAKED'
SMOKE_FAILURE = 'SMOKE_FAILURE'
SMOKE_BRAKED = 'SMOKE_BRAKED'
BAKING = 'BAKING'
BAKE_SUCCESS = 'BAKE_SUCCESS'
BAKE_SUCCESS_BRAKED = 'BAKE_SUCCESS_BRAKED'
BAKE_FAILURE_BRAKED = 'BAKE_FAILURE_BRAKED'
BAKE_FAILURE = 'BAKE_FAILURE'
BAKE_BRAKED = 'BAKE_BRAKED'
ROLLING_OUT = 'ROLLING_OUT'
ROLLOUT_SUCCESS = 'ROLLOUT_SUCCESS'
ROLLOUT_SUCCESS_BRAKED = 'ROLLOUT_SUCCESS_BRAKED'
ROLLOUT_FAILURE_BRAKED = 'ROLLOUT_FAILURE_BRAKED'
ROLLOUT_FAILURE = 'ROLLOUT_FAILURE'
ROLLOUT_BRAKED = 'ROLLOUT_BRAKED'
SUCCESS = 'SUCCESS'
FAILURE = 'FAILURE'
REVOKED = 'REVOKED'


# DeploymentBatch Statuses
PENDING = PENDING
DEPLOYING = 'DEPLOYING'
SUCCESS = SUCCESS
FAILURE = FAILURE
REVOKED = REVOKED


# DeploymentTarget Statuses
PENDING = PENDING
DISABLING = 'DISABLING'
DISABLE_SUCCESS = 'DISABLE_SUCCESS'
DISABLE_FAILURE = 'DISABLE_FAILURE'
ENABLING = 'ENABLING'
ENABLE_SUCCESS = 'ENABLE_SUCCESS'
ENABLE_FAILURE = 'ENABLE_FAILURE'
SUCCESS = SUCCESS
FAILURE = FAILURE
REVOKED = REVOKED
