from roll_engine import constants as _


# Deployment status SETS
FAILURES = [_.SMOKE_FAILURE, _.BAKE_FAILURE, _.ROLLOUT_FAILURE, _.FAILURE]
HALTED = [_.SUCCESS, _.REVOKED]
BREAKPOINTS = [_.SMOKE_FAILURE, _.SMOKE_SUCCESS, _.BAKE_FAILURE,
               _.BAKE_SUCCESS, _.ROLLOUT_FAILURE, _.ROLLOUT_SUCCESS,
               _.FAILURE]
RUNNINGS = [_.PENDING, _.SMOKING, _.BAKING, _.ROLLING_OUT]
BRAKED = [_.SMOKE_BRAKED, _.BAKE_BRAKED, _.ROLLOUT_BRAKED,
          _.SMOKE_SUCCESS_BRAKED, _.BAKE_SUCCESS_BRAKED,
          _.ROLLOUT_SUCCESS_BRAKED, _.SMOKE_FAILURE_BRAKED,
          _.BAKE_FAILURE_BRAKED, _.ROLLOUT_FAILURE_BRAKED]
SMOKES = [_.SMOKE_SUCCESS, _.SMOKE_FAILURE, _.SMOKE_BRAKED, _.SMOKING]
BAKES = [_.BAKE_SUCCESS, _.BAKE_FAILURE, _.BAKE_BRAKED, _.BAKING]
ROLLOUTS = [_.ROLLOUT_SUCCESS, _.ROLLOUT_FAILURE,
            _.ROLLOUT_BRAKED, _.ROLLING_OUT]

ENDPOINTS = [_.SUCCESS, _.FAILURE, _.REVOKED, _.SMOKE_SUCCESS, _.SMOKE_FAILURE] + BRAKED


# DeploymentTarget status
SKIPPING = 'SKIPPING'
DOWNLOADING = 'DOWNLOADING'
DOWNLOAD_SUCCESS = 'DOWNLOAD_SUCCESS'
DOWNLOAD_FAILURE = 'DOWNLOAD_FAILURE'
INSTALLING = 'INSTALLING'
INSTALL_SUCCESS = 'INSTALL_SUCCESS'
INSTALL_FAILURE = 'INSTALL_FAILURE'
VERIFYING = 'VERIFYING'
VERIFY_SUCCESS = 'VERIFY_SUCCESS'
VERIFY_FAILURE = 'VERIFY_FAILURE'

# Packge status
PENDING = _.PENDING
PACKING = 'PACKING'
SUCCESS = _.SUCCESS
FAILURE = _.FAILURE
CONNECT_ERROR = 'CONNECT_ERROR'

# Container type, use incre deploy when it belongs to this array
INCRE_DEPLOY_CONTAINER = ['netxml']
