#! /bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="tars daemon"
NAME=tarsd
DAEMON=$(which uwsgi)
CONFIGFILE=/var/www/$NAME.ini
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

set -e
[ -x "$DAEMON" ] || exit 0

do_start() {
    if ! pidof $DAEMON >/dev/null; then
        $DAEMON --pidfile=$PIDFILE --ini=$CONFIGFILE
    else
         echo "uwsgi already running"
    fi
    echo "$DAEMON STARTED."
}

do_stop() {
    if pidof $DAEMON >/dev/null; then
        $DAEMON --stop $PIDFILE
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f $PIDFILE
    else
        echo "uwsgi not running"
    fi
}

do_reload() {
    $DAEMON --reload $PIDFILE || echo -n "uwsgi can't reload"
}

do_status() {
    ps aux|grep $DAEMON
}

case "$1" in
 status)
    echo -en "Status $NAME: \n"
    do_status
 ;;
 start)
    echo -en "Starting $NAME: \n"
    do_start
 ;;
 stop)
    echo -en "Stopping $NAME: \n"
    do_stop
 ;;
 restart)
    echo -en "Restarting $NAME: \n"
    do_stop

    n=0
    until [ $n -ge 50 ]; do
        if ! pidof $DAEMON >/dev/null; then
            break
        fi
        n=$(( n+1 ))
        sleep 0.1
    done

    do_start
 ;;
 reload|graceful)
    echo -en "Reloading $NAME: \n"
    do_reload
 ;;
 *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
    exit 3
 ;;
esac

exit 0
